# Swagger
springdoc:
  swagger-ui.path: '/swagger-ui.html'
  swagger-ui.url: 'docs/api-contract.yml'
  swagger-ui.enabled: 'true'

# Database configuration
spring:
  web:
    resources:
      static-locations: 'classpath:/static/'

# Logger - Debug logs for DispatcherServlet (to see incoming requests and responses) and for our packages
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com:
      matias:
        fitnessapp: DEBUG
    org:
      springframework:
        jdbc:
          core: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG